PL/Controllers/RepartidorController.cs
using BL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI.WebControls.WebParts;

namespace PL.Controllers
{
    public class RepartidorController : Controller
    {
        // GET: Repartidor
        [HttpGet]
        public ActionResult GetAll()
        {
            ML.Repartidor repartidor = new ML.Repartidor();
            ServiceReference1.RepartidorServiceClient repartidorWCF = new ServiceReference1.RepartidorServiceClient();
            // se llama servicio 
            var result = repartidorWCF.GetAll(repartidor);
            if (result.Correct) {
                repartidor.Repartidores = result.Objects.ToList();
            }
            else
            {
                return View();
            }
            return View(repartidor);
        }
        [HttpGet]
        public ActionResult Form(int? IdRepartidor)
        {
            ML.Repartidor repartidor = new ML.Repartidor();
            if(IdRepartidor != null)
            {
                ServiceReference1.RepartidorServiceClient RepartidorWCF = new ServiceReference1.RepartidorServiceClient();
                var result = RepartidorWCF.GetById(repartidor);
                if (result.Correct)
                {
                    repartidor = (ML.Repartidor)result.Object;
                }
               
                
            }
            else
            {
                return View();
            }
            return View(repartidor);


        }
        [HttpPost]
        public ActionResult Form(ML.Repartidor repartidor)
        {
            if(repartidor.IdRepartidor == 0)
            {
                ServiceReference1.RepartidorServiceClient repartidorWCF = new ServiceReference1.RepartidorServiceClient();
                var result = repartidorWCF.Add(repartidor);
                if (result.Correct)
                {
                    ViewBag.Mensaje = "Se ha registrado correctamente el repartidor ";
                }
                else
                {
                    ViewBag.Mensaje = "Error al registrar el repartidor";
                }

            }
            else
            {
                ServiceReference1.RepartidorServiceClient repartidorWCF = new ServiceReference1.RepartidorServiceClient();
                var result = repartidorWCF.Update(repartidor);
                if (result.Correct)
                {
                    ViewBag.Mensaje = "Se ha actualizado correctamente el repartidor";

                }
                else 
                {
                    ViewBag.Mensaje = "Error al actualizar el repartidor";
                
                }
            }
            return PartialView("Modal");
        }
        public ActionResult Delete(ML.Repartidor repartidor)
        {
            ServiceReference1.RepartidorServiceClient repartidorWCF = new ServiceReference1.RepartidorServiceClient();
            var result = repartidorWCF.Delete(repartidor);
            if (result.Correct)
            {
                ViewBag.Mensaje = "Se ha eliminado correctamente el repartidor";

            }else
            {
                ViewBag.Mensaje = "Error al eliminar el repartidor";
            }
            return PartialView("Modal");
        }
        
    }
}

PL/Controllers/UsuarioController.cs
using BL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PL.Controllers
{
    public class UsuarioController : Controller
    {
        // GET: Usuario
        [HttpGet]
        public ActionResult GetAll()
        {
            
            ML.Usuario usuario= BL.Usuario.GetAll();
            if (usuario.Correct)
            {
                usuario.Usuarios = usuario.Objects;
                return View(usuario);
            }
            else
            {
                return View();
            }
        }
        [HttpGet]
        public ActionResult Form(int? IdUsuario)
        {
            ML.Usuario usuario = new ML.Usuario();
            usuario.Rol = new ML.Rol();

            ML.Rol rolG = BL.Rol.GetAll(); 
            if (IdUsuario != null)
            {
                ML.Usuario usuarioG = BL.Usuario.GetById(IdUsuario.Value);
                if (usuarioG.Correct)
                {
                    usuario = (ML.Usuario)usuarioG.Object;
                    usuario.Rol.Roles = rolG.Objects;
                }
            }
            else
            {
                usuario.Rol.Roles = rolG.Objects;
            }
            return View(usuario);
        }
        [HttpPost]
        public ActionResult Form(ML.Usuario usuario)
        {
            if (usuario.IdUsuario == 0)
            {
                ML.Usuario usuarioE = BL.Usuario.Add(usuario);
                if (usuarioE.Correct)
                {
                    ViewBag.Mensaje = "Se ha registrado correctamente el usuario";
                    ViewBag.Valido = false;
                }
                else 
                {
                    ViewBag.Mensaje = "Error al registrar el usuario";
                    ViewBag.Valido = false;
                }
                
            }
            else
            {
                ML.Usuario usuarioE = BL.Usuario.Update(usuario);
                if (usuarioE.Correct)
                {
                    ViewBag.Mensaje = "Se ha actualizado correctamente el usuario";
                    ViewBag.Valido = false;

                }
                else
                {
                    ViewBag.Mensaje = "Error al actualizar el usuario";
                    ViewBag.Valido = false;

                }
            }
            return PartialView("Modal");

        }
        public ActionResult Delete(int IdUsuario)
        {
            ML.Usuario usuario = BL.Usuario.Delete(IdUsuario);
            if(usuario.Correct)
            {
                ViewBag.Mensaje = "Se ha Eliminado correctamente el usuario";
                ViewBag.Valido = false;
            }
            else
            {
                ViewBag.Mensaje = "Error al eliminar el usuario";
                ViewBag.Valido = false;
            }
            return PartialView("Modal");
        }

        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public ActionResult GetEmail(ML.Usuario usuario)
        {
            string email = usuario.Email;
            string password = usuario.Password;

            usuario = BL.Usuario.GetEmail(email);
            //Session["idRol"] = usuario.Rol.IdRol;
            if (usuario.Correct) 
            {
                usuario = (ML.Usuario)usuario.Object;
                Session["idRol"] = usuario.Rol.IdRol;
                if (password == "12345")
                {
                    Session["IdUsuario"] = usuario.IdUsuario;
                    return RedirectToAction("Index", "Home");
                    
                }
                else
                {
                    ViewBag.valido = true;
                    ViewBag.Mensaje = "Error contraseña incorrecta";
                }
            }
            else
            {
                ViewBag.valido = true;
                ViewBag.Mensaje = "Error contraseña incorrecta";
            }
            return PartialView("Modal");
        }

    }
}

PL/Views/Repartidor/Form.cshtml
@model ML.Repartidor
@{
    ViewBag.Title = "Form";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="text-lg-start">
    <h2>Usuario</h2>
    <h5>Ingrese los datos del usuario</h5>
</div>
<hr />
@using (Html.BeginForm("Form", "Repartidor", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.HiddenFor(Model => Model.IdRepartidor)

    <div class="container text-center">
        <div class="row align-items-start">


            <div class="col">
                <div class="col-md-6">
                    @Html.LabelFor(model => Model.Nombre, new { @class = "hidden" })
                    @Html.TextBoxFor(model => Model.Nombre, new { @class = "form-control hidden" })
                </div>
                <div class="col-md-6">
                    @Html.LabelFor(model => Model.UnidadEntrega.IdUnidad, new { @class = "hidden" })
                    @Html.DropDownListFor(model => Model.UnidadEntrega.IdUnidad, new SelectList(Model.UnidadEntrega.Unidades, "IdUnidad", "Placas"), "Selecciona el area correspondiente", new { @class = "form-select hidden" })
                </div>
                <div class="col-md-6">
                    @Html.LabelFor(model => Model.FechaIngreso, new { @class = "hidden" })
                    @Html.TextBoxFor(model => Model.FechaIngreso, new { @class = "form-control hidden", @type = "date" })
                </div>

            </div>


            <div class="col">
                <div class="col-md-6">
                    @Html.LabelFor(model => Model.ApellidoPaterno, new { @class = "hidden" })
                    @Html.TextBoxFor(model => Model.ApellidoPaterno, new { @class = "form-control hidden", @type = "password" })
                </div>
                <div class="col-md-6">
                    @if (Model.Imagen == "" || Model.Imagen == null)
                    {
                        <img id="img" src="https://static.vecteezy.com/system/resources/thumbnails/002/318/271/small/user-profile-icon-free-vector.jpg" width="200" height="200" />
                        <input id="Imagen" name="Imagen" type="file" class="form-control" onchange="ValidarImagen(), visualizarImagen(this)" />
                    }
                    else
                    {

                        <img id="img" src="data:imagen/*;base64,@Model.Imagen" width="50" ,height="50" />
                        <input id="Imagen" name="Imagen" type="file" class="form-control" onchange="ValidarImagen(), visualizarImagen(this)" />
                    }
                </div>
            </div>


            <div class="col">
                <div class="col-md-6">
                    @Html.LabelFor(model => Model.ApellidoMaterno, new { @class = "hidden" })
                    @Html.TextBoxFor(model => Model.ApellidoMaterno, new { @class = "form-control hidden" })
                </div>

                <div class="col-md-6">
                    @Html.LabelFor(model => Model.Telefono, new { @class = "hidden" })
                    @Html.TextBoxFor(model => Model.Telefono, new { @class = "form-control hidden" })
                </div>
            </div>
        </div>
    </div>
    <div class="text-center">
        <button class="btn btn-success" type="submit"><i class="fa-solid fa-floppy-disk"></i> Guardar</button>
        <a id="btnCancelar" class="btn btn-danger" href="@Url.Action("GetAll", "Repartidor")"><i class="fa-solid fa-right-from-bracket"></i> Volver</a>
    </div>
}

@Scripts.Render("~/bundles/jquery")
<script type="text/javascript">

    function ValidarImagen() {
        var extensionesPermitidas = ['jpeg', 'jpg', 'png'];
        var extensionArchivo = document.getElementById('Imagen').value.split('.').pop().toLowerCase();
        var isValidFile = false; //saber si es valida o no es valida
        for (var index in extensionesPermitidas) {
            if (extensionArchivo === extensionesPermitidas[index]) {
                isValidFile = true;
                break;
            }
        }
        if (!isValidFile) {
            alert('Las extensiones permitidas son : *.' + extensionesPermitidas.join(', *.'));
            $("#Imagen").val("")
        }
        return isValidFile;

    }
    function visualizarImagen(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();
            reader.onload = function (e) {
                $('#img').attr('src', e.target.result);
            };
            reader.readAsDataURL(input.files[0]);
        }
    }
</script>

PL/Views/Repartidor/GetAll.cshtml
@model ML.Repartidor
@{
    ViewBag.Title = "GetAll";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="text-lg-start">
    <h2>Usuarios</h2>
    <h5>Listas de usuarios registrados </h5>
</div>
<hr />
<a type="button" href="@Url.Action("Form", "Repartidor")" class="btn btn-outline-success btn-lg w-25 p-3"><i class="bi bi-person-add"></i></a>
<hr />

<table class="table">
    <thead>
        <tr>
            <th scope="col"></th>
            <th scope="col">Id Usuario</th>
            <th scope="col">UserName</th>
            <th scope="col">Id Rol</th>
            <th scope="col">Email</th>
            <th scope="col">Nombre</th>
            <th scope="col">Apellido paterno</th>
            <th scope="col">Apellido materno</th>
            <th scope="col"></th>
        </tr>
    </thead>
    <tbody>
        @foreach (ML.Repartidor repartidor in Model.Repartidores)
        {
            <tr>
                <th scope="row"><a type="button" class="btn btn-outline-warning btn-lg" href="@Url.Action("Form", "Usuario", new {IdRepartidor = repartidor.IdRepartidor })"><i class="bi bi-pencil-square"></i></a></th>
                <td>@repartidor.IdRepartidor</td>
                <td>@repartidor.Nombre</td>
                <td>@repartidor.ApellidoPaterno</td>
                <td>@repartidor.ApellidoMaterno</td>
                <td>@repartidor.UnidadEntrega.NumeroPlaca</td>
                <td>@repartidor.Telefono</td>
                <td>@repartidor.FechaIngreso</td>
                <td>@repartidor.Imagen</td>
                <td><a href="@Url.Action("Delete","Usuario" , new { IdRepartidor = repartidor.IdRepartidor})" onclick="return confirm('Estas seguro de eliminar este registro');" type="button" class="btn btn-outline-danger btn-lg"><i class="bi bi-trash3"></i></a>x</td>
            </tr>
        }
    </tbody>
</table>