PL/Controllers/PaqueteController.cs
using BL;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PL.Controllers
{
    public class PaqueteController : Controller
    {
        // GET: Paquete
        public ActionResult GetRastreo(ML.Paquete paqueteG)
        {
            ML.Paquete paquete= BL.Paquete.GetRastreo(paqueteG.CodigoRasdtreo);
            if (paquete.Correct)
            {
                paquete = (ML.Paquete)paquete.Object;
                return View(paquete);
            }
            else
            {
                return View();
            }           
        }
        public ActionResult Opciones()
        {
            return View();
        }
        [HttpGet]
        public ActionResult AddPaquete()
        {
            return View();
        }
        [HttpPost]
        public ActionResult AddPaquete(ML.Paquete paquete)
        {
            var send = BL.Email.sendMail(paquete);
            var enviar = BL.Mensaje.Enviar(paquete);
            ML.Paquete paquete2 = BL.Paquete.AddPaquete(paquete);
            
            if (paquete2.Correct)
            {
                ViewBag.Mensaje = "Se ha enviado el correo";
                ViewBag.valido = true;
            }
            else
            {
                ViewBag.Mensaje = "Error al enviar el Correo";
                ViewBag.valido = false;
            }
            return PartialView("Modal");
        }
       
        
    }
}

PL/Views/Paquete/AddPaquete.cshtml
@model ML.Paquete
@{
    ViewBag.Title = "AddPaquete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<style type="text/css">
    #map {
        height: 400px;
        width: 100%;
    }
</style>


<div class="text-lg-start">
    <h2>Paquete</h2>
    <h5>Ingrese los datos del Paquete</h5>
</div>

<hr />
@using (Html.BeginForm("AddPaquete", "Paquete", FormMethod.Post, new { enctype = "multipart/form-data" }))
{


    <div class="container text-center">
        <div class="row align-items-start">


            <div class="col">
                <div class="col-md-6">
                    @Html.LabelFor(model => Model.Detalle, new { @class = "hidden" })
                    @Html.TextBoxFor(model => Model.Detalle, new { @class = "form-control hidden" })
                </div>
                <div class="col-md-6">
                    @Html.LabelFor(model => Model.Peso, new { @class = "hidden" })
                    @Html.TextBoxFor(model => Model.Peso, new { @class = "form-control hidden" })
                </div>
                <div class="col-md-6">
                    @Html.LabelFor(model => Model.Correo, new { @class = "hidden" })
                    @Html.TextBoxFor(model => Model.Correo, new { @class = "form-control hidden" })
                </div>
                <div class="col-md-6">
                    @Html.LabelFor(model => Model.Telefono, new { @class = "hidden" })
                    @Html.TextBoxFor(model => Model.Telefono, new { @class = "form-control hidden" })
                </div>

            </div>


            <div class="col">
                <div class="col-md-6">
                    @Html.LabelFor(model => Model.DirrecionEntrega, new { @class = "hidden" })
                    @Html.TextBoxFor(model => Model.DirrecionEntrega, new { @class = "form-control hidden mb-3", @id = "txtEntrega", @onClick = "showEntrega()" })
                    <button type="button" class="btn btn-outline-warning mb-3" style="display: none;" id="btnEntrega" onclick="btnE()"><i class="bi bi-pencil"></i></button>

                </div>
                <div class="col-md-6">
                    @Html.LabelFor(model => Model.DirrecionOrigen, new { @class = "hidden" })
                    @Html.TextBoxFor(model => Model.DirrecionOrigen, new { @class = "form-control hidden mb-3", @id = "txtOrigen", @onClick = "showOrigen()" })
                    <button type="button" class="btn btn-outline-warning mb-3" style="display: none;" id="btnOrigen" onclick="btnO()"><i class="bi bi-pencil"></i></button>
                </div>
            </div>


        </div>
    </div>
    <div class="text-center">
        <button class="btn btn-success mb-3" type="submit"><i class="fa-solid fa-floppy-disk"></i> Confirmar Compra </button>

    </div>
    

}

@*Modla*@
<div class="modal fade" id="modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" onclick="modalClose()">×</button>
                <h4 class="modal-title">Direccion</h4>
            </div>

            <div class="modal-body">
                <div>
                    <div id="map"></div>

                </div>

            </div>


            <div class="modal-footer">
                <button type="button" class="btn btn-success m-1" id="btnUpdate" onclick="modalClose()">Guardar</button>
               
            </div>
        </div>
    </div>
</div>




@Scripts.Render("~/bundles/jquery")
<script type="text/javascript">

    //MODALES

    function showEntrega() {
        showModal();
        var x = document.getElementById("btnEntrega");
        if (x.style.display === "none") {
            x.style.display = "block";
        } 
    }
    function showOrigen() {
        showModal();
        var x = document.getElementById("btnOrigen");
        if (x.style.display === "none") {
            x.style.display = "block";
        }
    }

    function showModal() {
        $('#modal').modal("show");
        
    }

    function modalClose() {
        $('#modal').modal("hide");
    }
    //botones
    function btnE() {
        $('#txtEntrega').val('');
       
        $('#modal').modal("show");

    }
    function btnO() {
        $('#txtOrigen').val('');
        $('#modal').modal("show");
    }

    function myFunction() {
       
    }




    (g => { var h, a, k, p = "The Google Maps JavaScript API", c = "google", l = "importLibrary", q = "__ib__", m = document, b = window; b = b[c] || (b[c] = {}); var d = b.maps || (b.maps = {}), r = new Set, e = new URLSearchParams, u = () => h || (h = new Promise(async (f, n) => { await (a = m.createElement("script")); e.set("libraries", [...r] + ""); for (k in g) e.set(k.replace(/[A-Z]/g, t => "_" + t[0].toLowerCase()), g[k]); e.set("callback", c + ".maps." + q); a.src = `https://maps.${c}apis.com/maps/api/js?` + e; d[q] = f; a.onerror = () => h = n(Error(p + " could not load.")); a.nonce = m.querySelector("script[nonce]")?.nonce || ""; m.head.append(a) })); d[l] ? console.warn(p + " only loads once. Ignoring:", g) : d[l] = (f, ...n) => r.add(f) && u().then(() => d[l](f, ...n)) })({
        key: "AIzaSyCSKBDdPPlfca_zTwyxKiicRQn1qfgRjLw",
        v: "beta"
        // Add other bootstrap parameters as needed, using camel case.
        // Use the 'v' parameter to indicate the version to load (alpha, beta, weekly, etc.)
    });

    // Initialize and add the map
    let map;
    var marker;
    

    async function initMap() {
        // The location of Uluru
        const position = { lat: 19.430570307662446, lng: -99.16166352568936 };
        // Request needed libraries.

        const { Map } = await google.maps.importLibrary("maps");

        // The map, centered at Uluru
        map = new Map(document.getElementById("map"), {
            zoom: 13,
            center: position,
            mapId: "DEMO_MAP_ID",
        });

        // The marker, positioned at Uluru
        let infoWindow = new google.maps.InfoWindow({
            content: "Presiona la locacion",
            position: position,
        });
        infoWindow.open(map);

        var icone = {
            url: "https://cdn.icon-icons.com/icons2/690/PNG/512/24_Maps_icon-icons.com_61461.png", // url
            scaledSize: new google.maps.Size(80, 80), // scaled size
            origin: new google.maps.Point(0, 0), // origin
            anchor: new google.maps.Point(0, 0) // anchor
        };

        var icono = {
            url: "https://cdn.icon-icons.com/icons2/3783/PNG/512/navigation_map_maps_pin_icon_232077.png", // url
            scaledSize: new google.maps.Size(80, 80), // scaled size
            origin: new google.maps.Point(0, 0), // origin
            anchor: new google.maps.Point(0, 0) // anchor
        };


        //obtener la dirrecion
        google.maps.event.addListener(map, 'click', function (event) {
            
            infoWindow.close();
            var geocoder = new google.maps.Geocoder();
            geocoder.geocode({
                'latLng': event.latLng
            }, function (results, status) {
               
                if (status == google.maps.GeocoderStatus.OK) {
                    if (results[0]) {
                        if ($('#txtEntrega').val() === "") {

                            if ($('#txtEntrega').val() === "") {
                            $("#txtEntrega").val(results[0].formatted_address);
                                marker = new google.maps.Marker({
                                    map: map,
                                    icon: icone,
                                    position: results[0].geometry.location
                                });
                                // To add the marker to the map, call set
                                    marker.setMap(map);
                            }
                        } else if ($('#txtEntrega').val() !== "") {
                                                $("#txtOrigen").val(results[0].formatted_address);
                                                marker = new google.maps.Marker({
                                                    map: map,
                                                    icon: icono,
                                                    position: results[0].geometry.location
                                                });
                                                // To add the marker to the map, call setMap();
                                                marker.setMap(null);
                                                marker.setMap(map);
                        }
                         else{
                            marker.setMap(null);    
                            }
   
                    }

                }
                

            });
            marker.setMap(null);
        })
        function codeAddress() {
            var address = document.getElementById('txtdirecion').value;
            geocoder.geocode({ '"txtdirecion': address }, function (results, status) {
                if (status == 'OK') {
                    map.setCenter(results[0].geometry.location);
                    var marker = new google.maps.Marker({
                        map: map,
                        position: results[0].geometry.location
                    });
                } else {
                    alert('Geocode was not successful for the following reason: ' + status);
                }
            });
        }

    }
        initMap();
</script>

PL/Views/Paquete/CuerpoCoreo.cshtml
@model ML.Paquete
@{
    Layout = null;
}

<!doctype html>
<html lang="en-US">

<head>
    <meta content="text/html; charset=utf-8" http-equiv="Content-Type" />
    <title>Resumen de Compra</title>
    <meta name="description" content="Resumen de la compra">
    <style type="text/css">
        a:hover {
            text-decoration: underline !important;
        }
    </style>
</head>

<body marginheight="0" topmargin="0" marginwidth="0" style="margin: 0px; background-color: #f2f3f8;" leftmargin="0">
    <table class="table">
        <thead>
            <tr>
                <th scope="col">Detalle</th>
                <th scope="col">Peso</th>
                <th scope="col">Dirrecion de destino </th>
                <th scope="col">Dirrecion de origen  </th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <th scope="row">@Model.Detalle</th>
                <td>@Model.Peso</td>
                <td>@Model.DirrecionEntrega</td>
                <td>@Model.DirrecionOrigen</td>
                
            </tr>

        </tbody>
    </table>

</body>

</html>

PL/Views/Paquete/GetRastreo.cshtml
@model ML.Paquete
@{
    ViewBag.Title = "GetRastreo";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<style type="text/css">
    #map {
        height: 400px;
        width: 100%;
    }
</style>
<div class="text-lg-start">
    <h2>Paquete</h2>
</div>
<hr />

@using (Html.BeginForm("GetRastreo", "Paquete", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <form>
        <label for="input" class="form-label">Codigo de Rastreo </label>
        <div class="mb-3">
            @Html.TextBoxFor(model => Model.CodigoRasdtreo, new { @class = "form-control " })
        </div>

        <button class="btn btn-outline-success" type="submit" id="btnBuscar">Search</button>
    </form>
}

@if (Model == null || Model.IdPaquete == null)
{
    <div class="alert alert-success" role="alert">
        Error Vulva a ingresar el codigo de rastreo o ingresalo.
    </div>

}
else
{
    <table class="table">
        <thead>
            <tr>
                <th scope="col">No. Paquete</th>
                <th scope="col">Codigo de Ratreo </th>
                <th scope="col">Peso</th>
                <th scope="col">Dirrecion de destino </th>
                <th scope="col">Dirrecion de origen  </th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <th scope="row">@Model.IdPaquete</th>
                <td>@Model.CodigoRasdtreo</td>
                <td>@Model.Peso</td>
                <td>@Model.DirrecionEntrega</td>
                <td>@Model.DirrecionOrigen</td>
            </tr>

        </tbody>
    </table>




}

PL/Views/Paquete/Modal.cshtml
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script src="http://bootboxjs.com/bootbox.js"></script>
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

<div class="modal" tabindex="-1" role="dialog" id="Modal">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Aviso</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <h5>@ViewBag.Mensaje</h5>
            </div>
            <div class="modal-footer">
                @*@Html.ActionLink("Regresar", "GetAll", "Materia", htmlAttributes: new { @class = "btn btn-danger" })*@
                @Html.ActionLink("Vale", "AddPaquete", "Paquete", htmlAttributes: new { @class = "btn btn-danger" })
            </div>
        </div>
    </div>
</div>

<script>$('#Modal').modal();</script>

PL/Views/Paquete/Opciones.cshtml
@{
    ViewBag.Title = "Opciones";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<style type="text/css">


    @@import url(https://fonts.googleapis.com/css?family=Oswald|Roboto|Slabo+27px);

    body {
        background: #ececec;
    }

    h1 {
        font-size: 32px;
        margin-top: 30px;
        font-family: "Oswald", sans-serif;
        text-align: center;
    }

    .blog-wrapper {
        padding: 15px;
        display: flex;
        flex-direction: row;
        justify-content: center;
        flex-wrap: wrap;
    }

        .blog-wrapper .blog-card {
            -webkit-transition: 0.3s;
            -moz-transition: 0.3s;
            transition: 0.3s;
            max-width: 300px;
            margin: 15px;
            background: #fff;
            border: 1px solid #CB6074;
            text-align: center;
            cursor: pointer;
        }

            .blog-wrapper .blog-card:hover {
                box-shadow: 0 3px 10px 0 rgba(0, 0, 0, 0.1);
            }

                .blog-wrapper .blog-card:hover .card-img img {
                    opacity: 0.8;
                }

            .blog-wrapper .blog-card .card-img {
                position: relative;
                text-align: center;
                background: #CB6074;
            }

                .blog-wrapper .blog-card .card-img img {
                    -webkit-transition: 0.3s;
                    -moz-transition: 0.3s;
                    transition: 0.3s;
                    max-height: 180px;
                    width: 100%;
                    border-bottom: 4px solid #CB6074;
                }

                .blog-wrapper .blog-card .card-img:before {
                    content: "";
                    position: absolute;
                    bottom: -8px;
                    left: 50%;
                    margin-left: -10px;
                    width: 0;
                    height: 0;
                    border-top: solid 10px #CB6074;
                    border-left: solid 10px transparent;
                    border-right: solid 10px transparent;
                }

                .blog-wrapper .blog-card .card-img h1 {
                    position: absolute;
                    margin: 0;
                    font-size: 42px;
                    bottom: 15px;
                    width: 100%;
                    color: #fff;
                    font-family: "Slabo 27px", serif;
                }

            .blog-wrapper .blog-card .card-details {
                margin-top: 30px;
                font-family: "Roboto", sans-serif;
                color: #3C3C3C;
            }

                .blog-wrapper .blog-card .card-details span {
                    padding: 0 30px;
                }

                    .blog-wrapper .blog-card .card-details span i {
                        margin-right: 5px;
                    }

            .blog-wrapper .blog-card .card-text {
                padding: 30px 15px;
                font-family: "Roboto", sans-serif;
                line-height: 22px;
            }

            .blog-wrapper .blog-card .read-more {
                -webkit-transition: 0.3s;
                -moz-transition: 0.3s;
                transition: 0.3s;
                display: inline-block;
                width: auto;
                text-align: center;
                text-transform: uppercase;
                background: #CB6074;
                color: #fff;
                padding: 15px;
                margin-bottom: 30px;
                font-family: "Oswald", sans-serif;
            }

                .blog-wrapper .blog-card .read-more:hover {
                    background: #943143;
                }
</style>

<div class="text-lg-start">
    <h2>Paquete</h2>
</div>
<hr />

<div class="blog-wrapper">
    <div class="blog-card">
        <div class="card-img">
            <img src="https://th.bing.com/th/id/R.2e0e58bb40f733f62fa034b30a9e6d9f?rik=UnJeWFT3CPtTOA&riu=http%3a%2f%2fwww.rapidocargo.hn%2fwp-content%2fuploads%2f2020%2f08%2fparcel-delivery-service-W986JQL.jpg&ehk=MaUSuBshrv0lko9I2s6eKJwtmxi4ulm4VGRDr7ANxLk%3d&risl=&pid=ImgRaw&r=0">
            <h2>Generar guia</h2>
        </div>
         <div class="card-text" ><i class="bi bi-box-seam " style="font-size:xx-large"></i></div>
        <a class="read-more" href="@Url.Action("AddPaquete", "Paquete")"><i class="bi bi-plus"></i></a>
    </div>
    <div class="blog-card">
        <div class="card-img">
            <img src="https://st2.depositphotos.com/1008801/10418/v/950/depositphotos_104182752-stock-illustration-folded-maps-with-color-point.jpg">
            <h2>Rastrear paquete</h2>
        </div>
       
        <div class="card-text"><p><i class="bi bi-geo-alt"  style="font-size:xx-large"></i></p></div>
        <a class="read-more" href="@Url.Action("GetRastreo", "Paquete")"><i class="bi bi-plus"></i></a>
    </div>
    <div class="blog-card">
        <div class="card-img">
            <img src="https://i0.pngocean.com/files/126/839/781/call-centre-customer-service-computer-icons-help-desk-telephone-call-others.jpg">
            <h2>Reportar/Asistencia</h2>
        </div>
       
        <div class="card-text"><p><i class="bi bi-telephone" style="font-size:xx-large"></i></p></div>
        <div class="read-more"><i class="bi bi-plus"></i></div>
    </div>
</div>